### PR TITLE
feat: pdf viewer swap & flicker problem fix

### LINKED ISSUE #472: Consider replacing current PDF viewer with https://www.embedpdf.com/
Current PDF viewer causes PDF flashes when + or -, which triggers epilepsy. Use this library to fix the issue

spsl mention for suggestion library: @mglsj

### PR DESCRIPTION
**Pull request by Gslmao**
## 📌 Purpose
Migrates the PDF viewer from react-pdf to embedpdf with the Pdfium WASM engine for improved rendering performance and a more modular plugin architecture.
---

## Corresponding issue: closes #472

---

## 🖼️ Showcase
Desktop View
image

Desktop view fullscreen
image

Mobile View
image

Mobile View Fullscreen
image

---

## 🔧 Changes
- **Engine**: Swapped `react-pdf` for embedpdf with viewport, scroll, zoom, render, document manager, and export plugins. 
- **Scroll & Zoom**: Removed manual `pageRefs` scroll tracking, `offsetTop` math, and the `wheel` event handler.
- **Toolbar**: Extracted into a standalone memoised `Controls` component. Added a `useBreakpoint` hook to handle responsive layout, consolidating the three previously duplicated toolbar variants (mobile, desktop, fullscreen) into one component with a resolved layout per breakpoint.
- **Performance**: `toggleFullscreen`, `handleDownload`, and the plugins array are all stabilised with `useCallback`/`useMemo` to prevent unnecessary re-renders of the memoised `Controls`.
---

## ➕ Additional Notes
- The flickering of the pages when zooming and in and out was fixed

### CODE REVIEW

**Comment by YOGESH-08** [comment]
remove the oldPdf Viewer if it is not used anymore

**Comment by YOGESH-08** [comment]
**Great ! flickering issue is solved.**

If wheel handler is removed, then try adding embedpdf's built in support for that. 
Zoom in/out on mouse wheel is required for better UX.

File: src/components/newPdfViewer.tsx [hunk 1]
```diff
@@ -0,0 +1,355 @@
...
+interface PdfViewerProps {
+  url: string;
+  name: string;
+}
+
+function useBreakpoint() {
+  const [width, setWidth] = useState(() => window.innerWidth);
+
+  useEffect(() => {
+    setWidth(window.innerWidth);
```
Comment (YOGESH-08) [inline src/components/newPdfViewer.tsx:44]: initialize it with a constant and then update it using useEffect

**Comment by YOGESH-08** [comment]
update ur PR title

**Comment by YOGESH-08** [comment]
why report button is enlarged a bit ?
