### PR TITLE
Fix: Filter error on navigated page (401)

### LINKED ISSUE #401: Filter error on navigated page
**Describe the bug**
If a particular subject has multiple pages of all exam papers, navigating to page 2 or further and applying filters leads to no papers being visible. Issue seems to be with how page navigation logic works.

**To Reproduce**
1. Open any subject (eg: Differential Equations)
2. Navigate to page 3.
3. Apply filter 'CAT-1'.
4. The page number shows page 3 of 2 and no papers are visible on that page. 
5. See error

**Expected behavior**
If filters are applied after navigating to further pages, it should bring you back to page 1 first and then showcase you the filters.

**Desktop (please complete the following information):**
 - Device: MacBook
 - OS: macOS 26
 - Browser: Safari

**Additional context**
Navigated page is consistent across subjects. Let's say you navigated to page 2 on compiler design and the looked up differential equations, you'll land on page 2 of differential equations and not page 1 even though you didn't navigate to page 2 for the current subject.

### PR DESCRIPTION
**Pull request by Advik-Gupta**
## 📌 Purpose
Fixes the bug where we got no papers found when applying filters after using pagination, and pagination carried over across subjects by resetting the page count when needed.

## Corresponding issue: closes #401

### CODE REVIEW

File: src/components/CatalogueContent.tsx [hunk 1]
```diff
@@ -60,6 +60,11 @@ const CatalogueContentInner = ({ subject }: { subject: string | null }) => {
     handleDownloadSelected,
   } = useFilters();
 
+  useEffect(() => {
+    console.log("subject", subject);
```
Comment (abhitrueprogrammer) [inline src/components/CatalogueContent.tsx]: remove console log

**Review by abhitrueprogrammer — CHANGES_REQUESTED** [review]

**Comment by abhitrueprogrammer** [comment]
sorry for the delay, forgot about the PR
